site:
  name: "ModelContextProtocol"
  base_url: "https://modelcontextprotocol.io"
  
crawling:
  include_patterns:
    - "/docs/*"
  exclude_patterns:
    - "/blog/*"
  max_depth: 5
  rate_limit: 1  # requests per second
  
extraction:
  content_selector: "main.content"
  title_selector: "h1.title"
  ignore_selectors:
    - "div.sidebar"
    - "footer"
    - "nav"
    
output:
  base_dir: "MCP_DOCS"
  file_prefix: "MCP_"
  naming_convention: "UPPERCASE_WITH_UNDERSCORES"
  
link_handling:
  internal_link_pattern: "^https?://modelcontextprotocol\\.io"
  preserve_anchor_links: true
  image_handling: "download"  # Options: download, reference

error_handling:
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  max_retries: 3
  retry_delay: 2  # seconds 